IE-bbuda/mozi-frontend

src/components/goal/RecommendCard.vue
src/components/goal/RecommendSection.vue
src/pages/goal/GoalDetailView.vue
src/pages/goal/RecommendationMainView.vue

목표 상세보기 수정(달성완료 화면), 추천카드(북마크, 점수 추가)
목표 상세보기 수정(달성완료 화면, 진행률 바 추가) 
추천카드(북마크, 점수 추가)
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes
```bash

목표 상세보기 수정(달성완료 화면), 추천카드(북마크, 점수 추가)

---

package-lock.json
package.json
src/api/policyApi.js
src/main.js
src/pages/policySearch/FilterLayout.vue
src/pages/policySearch/PolicySearchPage.vue
src/pages/policySearch/policyCard.vue
src/pages/policySearch/policyDetailPage.vue
src/pages/policySearch/policyFilter.vue
src/router/policySearch.js
vite.config.js

- 정책 탐색 페이지 프론트 구조 구현
- 필터 UI 및 정책카드 구성
- 정책 상세 페이지 및 라우팅 설정
**주요 변경사항:**
- `PolicySearchPage.vue`: 페이지 레이아웃 구성
- `FilterLayout.vue`: 관심지역, 연령 등 필터 선택 UI
- `policyCard.vue`: 정책 카드뷰 
- `policyDetailPage.vue`: 정책 상세페이지 구성
- `policyApi.js`: 정책 API 연동 파일 생성
<details>
</details>
> **Note**  
Closes #3
npm install
npm install bootstrap@5 axios moment
npm run build
```bash

feat: 정책 탐색페이지 레이아웃 및 필터 UI 구성

---

src/pages/goal/GoalDetailView.vue
vite.config.js

`GoalDetailView.vue` 목표 api 연결
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes 
```bash

feat: GoalDetailView.vue 목표 api 연결

---

.gitignore
src/components/layouts/DefaultLayout.vue
src/components/layouts/Footer.vue
src/components/layouts/Header.vue
vite.config.js

**주요 변경사항:**
<details>
</details>
> **Note**  
#28 
```bash

fix: 하단바 css 수정 오류 수정

---

src/api/goalApi.js
src/pages/goal/GoalCreateView.vue
src/pages/goal/GoalEditView.vue
src/pages/goal/GoalMainView.vue

**주요 변경사항:**
<details>
</details>
> **Note**  
```bash

[Fix]유저id 관련 프론트 파일내부 수정 변경사항 커밋

---

src/api/accountApi.js

feat: 목표 포함계좌 수정 요청 보내기 추가

---

src/api/goalApi.js

계좌 관련 목표 추가 수정에 필요한 함수 GoalApi.js파일에 추가
계좌 관련 목표 추가 수정에 필요한 함수 GoalApi.js파일에 추가
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

[Feature/goal crud] 계좌 관련 목표 추가 수정에 필요한 함수 GoalApi.js파일에 추가

---

src/components/goal/GoalForm.vue
src/pages/goal/GoalCreateView.vue
src/pages/goal/GoalEditView.vue
src/pages/goal/GoalMainView.vue
vite.config.js

**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

계좌 연결 변경사항 커밋

---

src/pages/goal/GoalDetailView.vue

**주요 변경사항:**
- 목표 상세페이지(`GoalDetailView.vue`) 계좌 연결
<details>
</details>
> **Note**  
Closes 
```bash

feat: 목표 상세페이지 계좌 연결

---

src/api/scrapApi.js
src/pages/search/policySearch/PolicySearchPage.vue
src/pages/search/policySearch/policyCard.vue
src/pages/search/policySearch/policyFilter.vue
vite.config.js

- scrapApi
- PolicySearchPage.vue
- PolicyFilter 
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

refactor: 스크랩 버그 수정 및 나이 필터링 기능 추가

---

src/api/accountApi.js
vite.config.js

**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

userid 가져오기설정

---

src/components/goal/GoalCard.vue
src/components/goal/GoalForm.vue
src/pages/goal/GoalCreateView.vue
src/pages/goal/GoalEditView.vue
src/pages/goal/GoalMainView.vue
vite.config.js

수정에서 날짜가 안 불러 와지는 버그 수정, ui수정, 계좌 연동 시 연동된 계좌 표시
**주요 변경사항:**
목표 관련 Vue
<details>
ui수정
날짜 변경 시 받아오는 데이터 형식이 달라서
이 부분 변환해주는 코드 삽입
</details>
> **Note**  
Closes #75
```bash

[Style,Fix] 수정에서 날짜가 안 불러 와지는 버그 수정, ui수정, 계좌 연동 시 연동된 계좌 표시

---

src/pages/HamburgerMenu.vue

**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

햄버거 바 UI 수정

---

src/pages/HamburgerMenu.vue

햄버거 바 스타일 수정
**주요 변경사항:**
햄버거 바 UI 수정 밑 뒤로가기 버튼 추가
<details>
HumburgerMenu.vue
</details>
> **Note**  
```bash

[Style] 햄버거 바 UI 수정 밑 뒤로가기 버튼 추가

---

src/components/goal/GoalEmptyCard.vue
src/pages/MainPage.vue

**주요 변경사항:**
목표 없을 때 메인 페이지 표시 카드 추가 밑 메인 페이지에 그 카드 표시 
<details>
목표 없을 때 메인 페이지 표시 카드 추가 밑 메인 페이지에 그 카드 표시 
</details>
> **Note**  
```bash

[Feature] 목표 없을 때 메인 페이지 표시 카드 추가 밑 메인 페이지에 그 카드 표시 

---

src/pages/HamburgerMenu.vue

feat: 햄버거 바에 로그아웃 버튼 추가

---

src/pages/MainPage.vue

**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

메인페이지 충돌 해결

---

src/pages/MainPage.vue
src/pages/account/BankAccountListPage.vue
src/pages/account/BankConnectPage.vue
src/pages/account/BankMainSettingPage.vue
src/pages/account/BankUnlinkPage.vue

- [] ✨ 새 기능 구현
- [X ] 🎨 스타일 변경
레이아웃 수정

feat: 레이아웃 수정

---

src/pages/account/BankSummaryPage.vue
vite.config.js

**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash

SummaryPage 라우터 수정

---

src/api/policyRecommendApi.js
src/api/scrapApi.js
src/pages/scrap/ScrapPage.vue
src/pages/search/financialSearch/financialCard.vue
src/pages/search/policySearch/PolicySearchPage.vue
src/pages/search/policySearch/policyCard.vue
src/pages/search/policySearch/policyDetailPage.vue
vite.config.js

**주요 변경사항:**
<details>
- 정책 탐색 jwt 기반 유저 방식으로 변경(하드코딩 제거)
- 금융 카드 스타일 추가
- 
</details>
> **Note**  
Closes #3
```bash

refact: 정책 탐색 usr id 하드코딩 제거 및 스타일 수정

---

src/pages/account/BankLoginModal.vue
src/pages/account/BankSummaryPage.vue

feat: 연결중 스타일 수정

---

src/components/goal/FinancialRecommendCard.vue
src/components/goal/GoalForm.vue
src/constants/enums.js
src/pages/goal/GoalDetailView.vue

**주요 변경사항:**
계좌 마스킹
자동 슬라이드 시간 수정
enum 수정
<details>
</details>
> **Note**  
Closes #141 
```bash

[Feature] 계좌 마스킹, 자동 슬라이드 시간 수정, enum 수정

---

src/components/profile/PersonalInfoPrompt.vue
src/pages/MainPage.vue
src/pages/user/PersonalInfo.vue
src/stores/auth.js

- 메인페이지 프롬포트 추가
**주요 변경사항:**
- MainPage.vue 수정
- PersonalInfo.vue 수정
- PersonalInfoPrompt.vue 수정
- 퍼스널 정보 입력이 거의 반 필수
- 그렇기 때문에 사용자가 바로 이동가능하게끔 유도

메인페이지 프롬포트 추가

---

src/pages/MainPage.vue
src/pages/account/BankAccountListPage.vue
src/pages/account/BankSummaryPage.vue

계좌 마스킹
계좌명이 길어짐에 따라 이상해진 계좌배치를 수정

feat: 계좌 마스킹, 계좌 배치 수정

---

src/pages/user/EditInfo.vue
src/pages/user/MyPage.vue

- 마이페이지 수정 api가 올바르지 않아 경로 수정
- 인증키 높이가 맞지 않아 수정
- 리다이렉트 오류 수정

fix: 개인정보 수정을 위한 api 변경

---

src/pages/MainPage.vue
src/pages/account/BankSummaryPage.vue
src/pages/auth/LoginPage.vue
src/pages/goal/GoalDetailView.vue
src/pages/goal/GoalMainView.vue
src/pages/recommend/RecommendPage.vue
src/pages/search/SearchGuidePage.vue
src/pages/search/financialSearch/DepositDetailPage.vue
src/pages/search/financialSearch/FinancialSearchPage.vue
src/pages/search/financialSearch/SavingDetailPage.vue
src/pages/search/financialSearch/financialFilter.vue
src/pages/search/policySearch/PolicySearchPage.vue
src/pages/search/policySearch/policyCard.vue
src/pages/search/policySearch/policyDetailPage.vue

- MainPage.vue 
- BankSummaryPage.vue 
- LoginPage.vue 
- GoalDetailView.vue 
- GoalMainView.vue 
- RecommendPage.vue 
- SearchGuidePage.vue 
- DepositDetailPage.vue 
- financialFilter.vue 
- FinancialSearchPage.vue 
- SavingDetailPage.vue 
- policyCard.vue 
- policyDetailPage.vue 
- PolicySearchPage.vue 
- 위 파일 레이아웃 공통화 작업 및 대표 색상으로 UI 색상 통일
**주요 변경사항:**
- 상단 뒤로가기 버튼 및 헤더 공통화 작업
- 탭 레이아웃 공통화 및 애니메이션 효과 적용
- 페이지 전반 공통 UI 및 대표색상 적용
> **Note**  
#147 
```bash

style: 페이지 전반 공통 UI 및 대표 색상 적용

---

src/components/goal/GoalCompletePopup.vue

feat: 목표 달성 팝업 개행 처리
`GoalCompletePopup.vue`
목표 달성 팝업 개행 처리
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes 
```bash

feat: 목표 달성 팝업 개행 처리

---

src/components/goal/GoalCompletePopup.vue

**주요 변경사항:**
`GoalCompletePopup.vue`
목표 달성 팝업 개행 처리
<details>
</details>
> **Note**  
Closes 
```bash

[Feature] 목표 달성 팝업 개행 처리

---

src/pages/MainPage.vue
src/pages/account/BankSummaryPage.vue
src/pages/goal/GoalMainView.vue

feat: 스크롤 없애기

---

src/pages/search/policySearch/PolicySearchPage.vue
src/pages/search/policySearch/policyDetailPage.vue

- 신청 url 버튼으로 변경
- 거주지역 스타일 깔끔하게 변경

정책 상세 URL 버튼 추가, 거주지역 스타일 수정

---

src/components/goal/PolicyRecommendCard.vue
src/components/goal/RecommendSection.vue
src/pages/recommend/policy/recommendPolicyCard.vue
src/pages/recommend/policyRecommendTab.vue

- 목표 상세에서 정책 추천 로딩 스피너 추가
- 추천탭 정책에 로딩 스피너 추가
- 목표 없을 때 목표 설정유도하는 디자인 통일

style: 정책 추천 로딩스피너 주가

---

src/pages/search/financialSearch/FinancialFilter.vue
src/pages/search/financialSearch/FinancialSearchPage.vue
src/pages/search/financialSearch/SavingDetailPage.vue

- 기간 필터링 적용 오류 수정
- 적금 상세 페이지 적립방식 기준 + 기간 오름차순 정렬 적용
**주요 변경사항:**
- 기간 필터링 적용 오류 수정
- 적금 상세 페이지 적립방식 기준 + 기간 오름차순 정렬 적용
- 필터 적용 후 페이지 이동 시 필터 해제 버그 수정
> **Note**  
```bash

fix: 기간 필터링 적용 오류 수정

---

src/pages/search/financialSearch/FinancialFilter.vue
src/pages/search/financialSearch/FinancialSearchPage.vue

**주요 변경사항:**
<details>
</details>
Closes #3
```bash

fix: 은행명 필터시 은행코드 노출 문제 수정
